### ISSUE TITLE
Artwork icon

### ISSUE THREAD

**Issue by MikiDi** [plepe/openstreetbrowser-categories-main#1]
Hi,
Just discovered OpenStreetBrowser via weeklyOSM ... great project!
I also very much like the idea of using the standardised 😁 emoji as icons.
The sleeping accomodation icon for an artwork ([here](https://github.com/plepe/openstreetbrowser-categories-main/blob/0a9958e711ea6fba7cad9bcfbcdbf33e135496bb/tourism_attractions.json#L30)) seems a little counter-intuitive however ... 🎨 perhaps?

Cheers

**Comment by plepe** [comment]
Ups, copy and paste error.
