### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [plepe/openstreetbrowser-categories-main#17]
Dear All,

I have translated [the categories into Hungarian](https://github.com/plepe/openstreetbrowser-categories-main/files/2445758/hu_json.zip). Please, upload the file [to its place](https://github.com/plepe/openstreetbrowser-categories-main/blob/master/lang/hu.json).
Thank you!

Gábor

**Comment by plepe** [comment]
Closed, as I already merged pull request #18.
