### ISSUE TITLE
Charging_Station should consider motorcar or bicycle

### ISSUE THREAD

**Issue by Fasse** [plepe/openstreetbrowser-categories-main#40]
You can add bicycle or car facitilies to the OpenStreetBrowser. The browser will show you the Charging_Stations.
Unlikely he ignore the attributes `motorcar=yes/no` or `bicycle=yes/no`. You will see all motorcar charging_stations if you view facilities for bicycles

**Comment by plepe** [comment]
Charging stations with bicycle=no were already excluded, but stations without information about bicycles were not. Now, charging stations need a bicycle tag (!=no) to be included.

**Comment by plepe** [comment]
Due to some technical difficulties the update will take some time until it appears on OpenStreetBrowser. Sorry!

**Comment by Fasse** [comment]
It would also be Great if charging-stations with motorcar or car will be considered in their category.

**Comment by plepe** [comment]
I just checked, charging stations with motorcar and motorcycle are included in the Transport/Individual Traffic/Amenities category. I improved the queries now, please check again. If you have a charging station which is not shown, could you please point a link to it?

Anyway, the technical problems are resolved and the changes are online.

**Comment by Fasse** [comment]
I checked it on the website and now it's working for both cases correct. Bicycles charging stations are only shown for bicycles and motorcar charging stations are only shown for individual transportations.

Thanks for the fix.

**Comment by plepe** [comment]
Perfect :-)
