### ISSUE TITLE
Display adresses with "contact:" keys.

### ISSUE THREAD

**Issue by CapitaineMoustache** [plepe/openstreetbrowser-categories-main#42]
In France and Germany, keys with "contact:" prefixe tend to be more common (see TagInfo: https://taginfo.openstreetmap.org/keys/?key=contact%3Ahousenumber#map) in order to add adresses on POI's without create duplicates with "addr:". An example: https://www.openstreetmap.org/node/8855169707.

Adresses are structured like this:
contact:housenumber
contact:street
contact:postcode
contact:city

It would be a good idea to display them in POI's poped boxes just as it is already the case with "addr:" tags.

**Comment by plepe** [comment]
Oh, I was not aware of these 'contact:' addresses. I think it's not a bad idea to use these, as they would reduce the amount of duplicate housenumbers in the OSM rendering. (quasi: "addr" for the physical building, "contact" for POIs in that building).

Added in 7c6177778dc91185594c8518b696ba9cf2091cd7
