### ISSUE TITLE
Detect correct network from semicolon-separated list

### ISSUE THREAD

**Issue by Hufkratzer** [plepe/openstreetbrowser-categories-main#43]
In example https://openstreetbrowser.org/#map=17/45.44823/11.66348&categories=hiking_routes,cycle_routes you can see that OSB does not recognize network=rwn;rcn
(route object is https://www.openstreetmap.org/relation/6048999)

Related discussions:
* https://lists.openstreetmap.org/pipermail/tagging/2021-August/062245.html
* https://github.com/waymarkedtrails/waymarked-trails-site/issues/321

**Comment by plepe** [comment]
fixed in 10af93ef8dce5cd097bfefa038eb187b0b982a8c

**Comment by Hufkratzer** [comment]
Now it looks like the network is detected correctly in the menu on the left, but on the map the route is drawn in blue = color for unknown network, (I marked it with "?????"):
![OSB](https://user-images.githubusercontent.com/5958184/130262704-3d90774e-b938-4e98-9bc0-e6cf96feba3e.jpg)

**Comment by plepe** [comment]
Thanks for pointing this out, the lists in the popups are rendered separately (from the category). Fixed in 169a50beeeb4c5d7a03a767604359aa2d285bf08. I also improved the style in 7f2990959c497b3ff557d32e61a0e0f8ecb8a8f8.

**Comment by Hufkratzer** [comment]
Now the infobox looks a bit strange if there are more than one routes on one way:
![OSB](https://user-images.githubusercontent.com/5958184/130332538-a07ed5e6-48e9-4f51-8ef2-0eee34d84aa8.jpg)
https://openstreetbrowser.org/#cycle_routes/member:w106937676&map=17/51.10066/13.62838&categories=cycle_routes

I am not sure for how long this is so, but a year ago I think it was better.

**Comment by plepe** [comment]
Sorry, I forgot to write that I already fixed that in right after your post: 4dd51b46e26b6f622515347c12e7e8ab6631ab43.

**Comment by Hufkratzer** [comment]
Thanks.

There is another strange problem here:

If I open the [link ](https://openstreetbrowser.org/#cycle_routes/member:w106937676&map=17/51.10066/13.62838&categories=cycle_routes) given [above](https://github.com/plepe/openstreetbrowser-categories-main/issues/43#issuecomment-903163659) in a new browser tab (Opera or Chrome), the cpu load on my (not very powerful) notebook goes up to at least 75% (sometimes earlier, sometimes later) within the first minute. After about 3 minutes (+/- 1) more the cpu load quite abruptly drops to a minimal level again, all without any further action from my side after opening the new browser tab with OSB. Sometimes this whole browser tab completely freezes for some minutes and then recovers, what is a bit disturbing.
