### ISSUE TITLE
vending=parcel_pickup;parcel_mail_in is now amenity=parcel_locker

### ISSUE THREAD

**Issue by kuba-medrek** [plepe/openstreetbrowser-categories-main#44]
Hello.
Tag `vending=parcel_pickup;parcel_mail_in` has just been replaced by `amenity=parcel_locker` in proposition: [Proposed_features/amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker).

Are you going to support new scheme?

**Comment by plepe** [comment]
Sure, why not. Apparently, I do not list any parcel handling machines at all. I would add it to the communications category. Shall I also add the old tagging as well?

I think, in a previous version, I had a category for all types of vending machines. I guess, I should re-create this one. I would include this there as well.

**Comment by plepe** [comment]
From now on, both the old tagging as well as the new tagging is included in the communications category. See d1fa17d35b9c6d713a0d4ff1770c8f47707f5de7 for details.

-> https://openstreetbrowser.org/#categories=communication

**Comment by plepe** [comment]
I announced this here: https://www.openstreetmap.org/user/skunk/diary/398522
