### ISSUE TITLE
Bicycle rentals other than amenity=bicycle_rental

### ISSUE THREAD

**Issue by stefanct** [plepe/openstreetbrowser-categories-main#46]
OSB does not find all bike rental POIs. There are (at least) two unsupported schemes:

 - [service:bicycle:rental](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:rental) (on hotels, bicycle shops etc.), [example](https://www.openstreetmap.org/node/1402012656)
 - [rental=bicycle](https://wiki.openstreetmap.org/wiki/Key:rental) (on shop=rental), [example](https://www.openstreetmap.org/way/422909172)

**Comment by plepe** [comment]
Thanks for notifying! I fixed that right away:
1. rental=bicycle will be included in the results, by 28d81a2bcb045df7590670d3bedd3988ec0274d4
2. the additional filter "bicycle rental" also includes these both tags: ee16462bff543809d4fa662ec3fbb7f91dfb43db

**Comment by stefanct** [comment]
Thanks!
BTW I noticed the minimum zoom level to be way too low to remain useful if you apply (such) filters. That's probably not only applicable to bicycle amenities but pretty much everything where you have set minimum zoom levels.

**Comment by plepe** [comment]
Moving this comment to a separate issue.
