### ISSUE TITLE
Miraculous steps

### ISSUE THREAD

**Issue by hungerburg** [plepe/openstreetbrowser-categories-main#56]
When I browse some extra-urban area, I notices paths with steps, where there are no steps mapped. Unfortunately this deep-link https://openstreetbrowser.org/#footways/w470024951/details does not work. Here to OSM https://www.openstreetmap.org/way/470024951 - How come?

**Comment by plepe** [comment]
Some compatibility problems with a newer LeafletJS version. Haven't found the reason yet, though :-(

**Comment by plepe** [comment]
That's not the symbol of a step, but of a combined cycle-/foot-way - which is also wrong, thanks for pointing out.

**Comment by plepe** [comment]
Paths should be shown correctly now (07ccd34262d87731926e52d57e6e92f19a741d9d). I also made the dashes for non-segregated cycleway/footways longer, so they are easier distinguishable ( c5d2052a4b5921ef15ab0087a14409fb8f226b44).
