### ISSUE TITLE
Pedestrian footways - some areas are missing

### ISSUE THREAD

**Issue by kayD** [plepe/openstreetbrowser-categories-main#67]
The new feature "pedestrian footways" is brilliant and also is a great aid to improve the map.

Cool that it also covers areas, however I found that a part of the market place in Würzburg is not shown:
Link: (https://www.openstreetbrowser.org/#map=18/49.79449/9.92908&basemap=osm-mapnik&categories=footways)
Observed: the market area in the center is not highlighted (the area around the "Marktbrunnen")

The issue is that this area is a multipolygon (https://www.openstreetmap.org/relation/3865559), and therefore has no "area=yes" tag, because it is implied (see https://wiki.openstreetmap.org/wiki/Relation:multipolygon).

**Comment by plepe** [comment]
Good catch, thanks for notifying!

I fixed it right away: 712263f8a5a02812f36580d5fe2bbd7d4753f253

**Comment by kayD** [comment]
Works perfectly now - that was blazing fast. Thanks so much!

**Comment by plepe** [comment]
You are welcome :-)

I recommend adding wikimedia_commons tags to the areas, (or even wikidata tags, if there is an entry - in Vienna for example, most squares have a wikidata entry):

* `wikimedia_commons`=`Category:Marienplatz (Würzburg)` for https://www.openstreetmap.org/way/12711063
* `wikidata`=`Q699937` for https://www.openstreetmap.org/way/30322134 resp. https://www.wikidata.org/wiki/Q699937
