### ISSUE TITLE
amenity=canteen

### ISSUE THREAD

**Issue by famo** [plepe/openstreetbrowser-categories-main#69]
Please add canteens to gastronomy.
https://wiki.openstreetmap.org/wiki/Tag:amenity=canteen

**Comment by plepe** [comment]
Done in 371057f8aed3d0e8e1c5b5ebb8e764ba4c185d7e.

I couldn't find a suiting icon, so it's using the default (the cutlery symbol). You could look through the [available icons](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Icons.md) and suggest one.

I also add amenity=canteen to the translation system. You are welcome to translate this here: https://weblate.openstreetbrowser.org/translate/openstreetbrowser/osm-tags/en/?type=translated&offset=65#translations
