### ISSUE TITLE
Add denotation=natural_monument to Culture - Media/Wikidata layer?

### ISSUE THREAD

**Issue by ivanbranco** [plepe/openstreetbrowser-categories-main#71]
Do you think it could be a good idea to add denotation=natural_monument trees in the OpenStreetMap Quality Control > Culture - Media/Wikidata layer? I often use OpenStreetBrowser before and during (via mobile) travels to find elements without images to shoot, and it would be cool to have remarkable trees included.

**Comment by plepe** [comment]
Sure, why not. Maybe also denotation=landmark?

**Comment by ivanbranco** [comment]
Personally I'm interested in denotation=natural_monument because is less subjective (at least here in Italy, were such trees are designated by the ministry of agricolture).

**Comment by plepe** [comment]
When looking through open issues, I found this one. I'm sorry, I must have forgotten!

I just implemented the change, it is already online: ab1fdd3171ad1ac38648ddb750755e406193a796

**Comment by plepe** [comment]
I also added the denotation=* tags to the translation system: https://weblate.openstreetbrowser.org/projects/openstreetbrowser/
