### ISSUE TITLE
Add support for newline `\n` in description and inscription

### ISSUE THREAD

**Issue by Nekzuris** [plepe/openstreetbrowser-categories-main#74]
Some description, inscription, and probably other tags use newlines, but they are currently not rendered in your UI.
[example](https://www.openstreetbrowser.org/#memorial/n9072532487&map=16/48.2493/7.1015&basemap=osm-mapnik&categories=memorial)

**Comment by plepe** [comment]
Thanks for the hint. I implemented this for description and inscription. If you find more tags, please tell me!

Change 5eefa42b416a8e8cc674ba2f1c7b3d586ace89e4

**Comment by Nekzuris** [comment]
iD also support it for note and fixme

**Comment by plepe** [comment]
'note' is currently not shown in any category. I updated the fixme category to break lines for `\n` (4015797d4bcee3fca4140dca8c36215231ad1ca8).
